/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package class24_graphics;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author estudiante
 */
public class frmGrafico extends javax.swing.JFrame {
    
    private boolean bandera = false;
    
    /**
     * Creates new form frmGrafico
     */
    public frmGrafico() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPartido1 = new javax.swing.JTextField();
        lblPartido1 = new javax.swing.JLabel();
        lblPartido2 = new javax.swing.JLabel();
        txtPartido2 = new javax.swing.JTextField();
        lblPartido3 = new javax.swing.JLabel();
        txtPartido3 = new javax.swing.JTextField();
        btnGraficar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtPartido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 54, 129, -1));

        lblPartido1.setText("Partido 1");
        getContentPane().add(lblPartido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 57, 48, -1));

        lblPartido2.setText("Partido 2");
        getContentPane().add(lblPartido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 80, 48, 20));
        getContentPane().add(txtPartido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 80, 129, -1));

        lblPartido3.setText("Partido 3");
        getContentPane().add(lblPartido3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 106, 48, 20));
        getContentPane().add(txtPartido3, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 106, 129, -1));

        btnGraficar.setText("Graficar");
        btnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGraficar, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 51, -1, 75));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarActionPerformed
        // TODO add your handling code here:
        bandera = true;
        repaint();
    }//GEN-LAST:event_btnGraficarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGrafico().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGraficar;
    private javax.swing.JLabel lblPartido1;
    private javax.swing.JLabel lblPartido2;
    private javax.swing.JLabel lblPartido3;
    private javax.swing.JTextField txtPartido1;
    private javax.swing.JTextField txtPartido2;
    private javax.swing.JTextField txtPartido3;
    // End of variables declaration//GEN-END:variables
    
    public void paint(Graphics g)
    { super.paint(g);
        if (bandera == true) {
            String s1 = txtPartido1.getText();
            String s2 = txtPartido2.getText();
            String s3 = txtPartido3.getText();
            int v1=Integer.parseInt(s1);
            int v2=Integer.parseInt(s2);
            int v3=Integer.parseInt(s3);
            int suma =v1+v2+v3;
            int grados1 = v1*360/suma;
            int grados2 = v2*360/suma;
            int grados3 = v3*360/suma;
            
            g.setColor(new Color(255,0,0));
            g.fillArc(50, 250, 200, 200, 0, grados1);
            g.fillRect(370, 250, 20, 20);
            g.drawString("Partido 1", 400, 270);
            
            g.setColor(new Color(0, 128, 0));
            g.fillArc(50, 250, 200, 200,grados1, grados2);
            g.fillRect(370, 280, 20, 20);
            g.drawString("Partido 2", 400, 300);            
            
            g.setColor(new Color(0, 0, 255));
            g.fillArc(50, 250, 200, 200,grados1+grados2,grados3);
            g.fillRect(370, 310, 20, 20);
            g.drawString("Partido 3", 400, 330);            
            
            
        }
    
    }
    
}
